### ISSUE TITLE
option to also display DOGE as fiat value

### ISSUE THREAD

**Issue by sweetppro** [electrumalt/electrum-doge#1]
It would be handy to have a fiat representation of how many DOGE are stored in the wallet somewhere on the main ui.

as in the image below would be ideal.
![doge](https://cloud.githubusercontent.com/assets/7323792/5325677/8a8c6816-7d3e-11e4-8ff5-06ab9b92c0e6.jpg)

**Comment by xilanma** [comment]
Thanks for the feature request, this will be available in next release :+1:
