### ISSUE TITLE
No Dogecoin electrum servers available

### ISSUE THREAD

**Issue by santzi** [electrumalt/electrum-doge#11]
Hi,

Client couldn't get connect any Dogecoin electrum server...is there any available?
If no, what might be the reason behind this?
I know that there are many people, who like to use Dogecoin Electrum client.

Unfortunately I haven't enough competence to fork BTC Electrum client/server python codes and make new ones to Dogecoin...I know there are huge amount of people who has.

**Comment by santzi** [comment]
I will close this issue. No valid anymore.

**Comment by JeremyRand** [comment]
If anyone is still interested in this, Namecoin's Electrum-NMC project maintains an AuxPoW branch of Electrum, which could be used as a base for a new Electrum-DOGE.  https://github.com/namecoin/electrum-nmc  Upstream ElectrumX is fine for the server-side.
