### ISSUE TITLE
 report-a-bug link is wrong

### ISSUE THREAD

**Issue by 777cool** [electrumalt/electrum-doge#2]
links to:

https://github.com/spesmilo/electrum/issues

not

https://github.com/electrumalt/electrum-doge/issues

**Comment by jflaloux** [comment]
There isn't a github for the site?

**Comment by 777cool** [comment]
fixed in 2.2

http://i.imgur.com/dmE0UVY.png

**Comment by xilanma** [comment]
@adrianwaj thanks, yes it was fixed I believe. 

@jflaloux I haven't pushed the site on Github yet but planning to do it :+1:

**Comment by jflaloux** [comment]
@xilanma just an information that may help you. You can actually host your site on github, that allows easy changes without ftp and everybody can request pull that you would just have to accept : https://pages.github.com/
