### ISSUE TITLE
Stuck transaction remains after broken no-sync was resolved

### ISSUE THREAD

**Issue by BuxtonTheRed** [electrumalt/electrum-doge#6]
I was affected by the can't-sync issue remaining with 2.2.0 but resolved by fixing the SSL issue on the server. (Was showing Blockchain of -1 blocks, etc.)

Foolishly, during that period of brokenness, I tried sending my Doge back to my Core wallet. That transaction was stuck Pending / Unconfirmed at the time (no surprise), and is now still very stuck after I am now successfully getting connected. The tx never made it on to the blockchain according to Dogechain's explorer. (TX ID is 020abda7940c4fd2fc4426de77b9bbba8a7179e12c3e5ae92d547640b3669aa7 )

Hopefully some screenshots will show up here:

![electrum-doge stuck tx](https://cloud.githubusercontent.com/assets/4097732/5428191/96382cda-83b1-11e4-92e1-2ce898564e3b.png)

![electrum-doge stuck details](https://cloud.githubusercontent.com/assets/4097732/5428207/1890d7b8-83b2-11e4-81ca-7e49ed481e5d.png)

I have installed E-D on my laptop, restored my wallet from the seed in use on my Desktop, and the same "successful inbound Ð1000 tx, stuck outbound Ð999" is showing up on there - so the stuck TX is not just stored locally on my desktop machine where the issue first came up.

I tried making a fresh transaction, but E-D is aware that I have this unconfirmed 999-doge transaction still pending, and thus sensibly tells me I don't have enough Doge balance available.

**Comment by xilanma** [comment]
That's pretty strange. If the tx is not on the network, it should not show up when you re-create the wallet. Can you click the Save button in the last screenshot, open the file in a text editor and paste the content here? I will try to propagate the transaction manually using dogecoind and see if it fixes the problem.

**Comment by BuxtonTheRed** [comment]
Tx file contents:

{
    "hex": "010000000119f8811994fb839aa5f2d44f219fc84a4299971bb299851c7e30a0cdd95644dc010000006c493046022100a1bb5f035dec872e12d030a87e37198fca87f86bffaf40f6ebe345f1852a24d9022100b89bae37f1b85aa0a060212b66dd3b808aeaffe1904fdd6c6580ad33e0ec1f3a012102ec343a41dcf6e417cf9022dfdfd9fd7c401360b1801ca651772013dc4a4d93c1ffffffff0200078142170000001976a9147ab54cd39d2408bf4bafe8b6c37908c981c4ccdb88acdcb4f505000000001976a914e0ef0a09ac920ee787baa37ef7f266d157e5d8e988ac00000000", 
    "complete": true
}

I have tried using **sendrawtransaction** in the Core wallet's Debug Console with the hex from that paste above, and the TX now shows up in my Core but shows as Unconfirmed, and also doesn't show in Dogechain. It's been a good few minutes now and the TX hasn't "moved" at all.

Maybe it's been accepted by the E-D server but for some reason it's not getting relayed? I did notice that E-D handles network fees differently to everything else, and it was putting a less-than-Ð1 fee on that transaction when I sent it. Maybe that's a problem?

**Comment by BuxtonTheRed** [comment]
I did have the idea to try exporting my privkeys out from E-D and importing in to Multidoge to regain control of the "unspent" (according to network consensus) coins - to effectively allow me to re-spend them from a different wallet and give it a more standard 1-Doge network fee.

Unfortunately, the Private Keys export tool (Wallet menu, Private keys, Export) doesn't work for me - it gets stuck at "Please wait... 24/25" and the Export button never gets enabled. This is the case on both my desktop and laptop machines.

**Comment by xilanma** [comment]
Ok, I will try to see how to fix this as soon as the server is back online. The database was corrupted for some reason and I had to rebuild it from scratch which takes few hours. :/

**Comment by BuxtonTheRed** [comment]
Just in case the Private Key export problem was being caused by some sort of interaction with the other issue, I uninstalled E-D from my laptop, removed its appdata folder, reinstalled with the wifi turned off (to keep it offline), and re-imported my seed.

Private Key export failed in the same way, only this time it got to 23/24 rather than 24/25.

This isn't a mega-urgent issue for me, because the amount of coins currently "stuck" in E-D is a tiny amount and is not causing me massive concerns or anxiety.

**Comment by xilanma** [comment]
By the way the private key export issue is a known issue in Electrum as well. I am waiting a fix from them to merge it so we don't diverge too much from the original code base. Meanwhile, you can give me a DOGE address and I'll send you.

**Comment by xilanma** [comment]
The server should be back online now. Is your transaction still stuck?

**Comment by BuxtonTheRed** [comment]
All is solved and fixed now - the erroneous stuck transaction had disappeared, leaving the original balance in the wallet, and a new outbound transaction sent successfully.

Thanks for the help.
