### ISSUE TITLE
Unable to Connect to Server

### ISSUE THREAD

**Issue by dylan-park** [electrumalt/electrum-doge#7]
When opening the wallet, not connected is displayed at the bottom left corner of the window and a red dot at the bottom right. I looked into the settings and nothing seems to be wrong there. I am connected to the internet, so it appears to ether be a server problem, or there is something going wrong when the client tries to communicate with the server. Anyone else getting this error?

**Comment by greenmo000** [comment]
Yes, same here.

**Comment by xilanma** [comment]
Sorry, the server is currently down due to database corruption. It can take many hours before the database is rebuilt. We are trying to find volunteers to open more servers so it doesn't happen in the future.

**Comment by dylan-park** [comment]
Alright that's fine. As long as it is not a problem with the application. Hopefully as this wallet grows more servers will become available!

**Comment by xilanma** [comment]
The server should be back online now.
